### ISSUE TITLE
Request needed permissions

### ISSUE THREAD

**Issue by flocke** [BennyKok/OpenLauncher#10]
I just noticed that the hide apps feature only works if I enable the Storage permissions manually.
Which is because the list of apps to hide is saved in _/sdcard/launcher.backup/appfilter.txt_ and not with the rest of the app data in _/data/data/com.benny.openlauncher/files_. Is this the intended behaviour?

1. If yes the app should request the Storage permission at some point, if not the storage location should be moved.
2. Why does the app implement the Phone and Contacts permissions?

**Comment by scoute-dich** [comment]
1. It was late and I was lazy. I changed it. appfilter.xml is now stored in app data directory.
2. I think it is/was used for the quickcenter, which is disabled at the moment (due to some issues).

I commented the unused permissions out.
