### ISSUE TITLE
The app drawer can't be opened under specific conditions.

### ISSUE THREAD

**Issue by dkanada** [BennyKok/OpenLauncher#13]
To reproduce the issue, set OpenLauncher as the default home. Next, click on OpenLauncher in the app drawer to open what I think is a second instance of the app. When in the second instance of the app, if home is pressed the first instance is opened and the app drawer icon doesn't work. The second instance of the app will also show up in the recent app list now and when swiped away will also cause the app drawer in the first instance to break. As far as I can tell, the issue only shows up when OpenLauncher is set as the default home.

**Comment by BennyKok** [comment]
OK I will look into the problem

**Comment by flocke** [comment]
Starting a second instance of a Launcher that is already running doesn't seem like a good idea anyways. In my opinion the icon in the app drawer should open the settings if the launcher is already running.
Or the icon should not even show up in the drawer, only a shortcut to the settings, like for example with Nova Launcher.

**Comment by BennyKok** [comment]
Right, that is a good idea

**Comment by BennyKok** [comment]
I have encounter the problem. and will fix this

**Comment by BennyKok** [comment]
Fixed
