### ISSUE TITLE
Allow dock sizes lower than 5

### ISSUE THREAD

**Issue by flocke** [BennyKok/OpenLauncher#14]
Could you lower the limit for the dock size to 4?
Now that swipe to open drawer works as expected I would like to get rid of the app drawer icon in the dock and only have the 4 app shortcuts.
I assume this should not be to hard to implement ...

**Comment by TeamBrainStorm** [comment]
I like this idea but I think we should keep the add app drawer action in
the settings so that if the user wants a app drawer they can have one
instead of having to swipe up to get to the apps

**Comment by flocke** [comment]
Yes, the app drawer action should of course still be present.
I just removed it, but I can still add it again without problems.

**Comment by TeamBrainStorm** [comment]
Then I think it's a great idea

But it's up to Benny ultimately :)

**Comment by BennyKok** [comment]
OK lower it

**Comment by BennyKok** [comment]
done
