### ISSUE TITLE
Remove apps from dock/desktop after uninstall.

### ISSUE THREAD

**Issue by flocke** [BennyKok/OpenLauncher#16]
I just noticed that apps shortcuts stay on the desktop after I uninstall them. For now it is no problem to remove them manually, but I think they should be deleted automatically once the app is removed.

**Comment by BennyKok** [comment]
Yeah, TeamBrainStorm has also told me before, thanks for opening an issue so I can keep track on the debugging progress

**Comment by BennyKok** [comment]
ok

**Comment by BennyKok** [comment]
fixed
