### ISSUE TITLE
Please cleanup repo and fix gitignore

### ISSUE THREAD

**Issue by gsantner** [BennyKok/OpenLauncher#28]
Please cleanup repo (with e.g. BFG - (https://rtyley.github.io/bfg-repo-cleaner/)) to remove previous artifacts, which do account a lot of space that should not be checked in a repo. To do this, you have to force push afterwards.

As you can see, one already needs 114 MB to download the latest state of the app, which is a lot. I can really think of persons being not able to submit simple patches, because of need to download so much stuff, which can make problem e.g. on mobile networks.
![grafik](https://cloud.githubusercontent.com/assets/6735650/24434281/e70f647e-142e-11e7-8a90-cadca4948762.png)

You can find an appropiate gitignore e.g. on <https://www.gitignore.io/> or <https://github.com/gsantner/memetastic/blob/master/.gitignore>

First a commit needs to cleanup current version + adding gitignore. BFG (e.g. strip blobs) will then remove old binaries - not currently checked in on master - files from history. (it will never touch current HEAD).

**Comment by BennyKok** [comment]
I really sorry cause I didn't use .gitignore when I first published this project, so some file was there all the time, now it reduced to about 5mb.

**Comment by gsantner** [comment]
@BennyKok 
This actually didn't fix it. What got once into git history stays in history. As said above, you can use e.g. bfg to remove that blobs from history.

![grafik](https://cloud.githubusercontent.com/assets/6735650/24472608/96b6786c-14c6-11e7-818e-368be037f130.png)

**Comment by gsantner** [comment]
@BennyKok @dkanada @scoute-dich 
Sat down for about an hour to fix everything. Removed pretty much every bad file from history.:tada: :tada: 

![grafik](https://cloud.githubusercontent.com/assets/6735650/24521808/a6620de0-158d-11e7-9f9a-4b327cf0545a.png) 
Commands I ran:
```
bfg --delete-files "*.{apk,dex,bin,zip,ap_,hprof,class,json,iml,aar,alloc,jar}" OpenLauncher
bfg --delete-files "R.{txt,java}" OpenLauncher
bfg --delete-files "Zeichnung.svg" OpenLauncher
bfg --delete-files "{abc_,appcompat_,design_,manifest-,vpi__}*" OpenLauncher
bfg --delete-files "{merger,workspace,build-info}.xml" OpenLauncher
cd OpenLauncher
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push --force
git push origin tags --force
```

Here's an list of files did not getting touched by this, I made sure strings.xml and java files e.g. didnt get rewritten: 
[unchanged.txt](https://github.com/BennyKok/OpenLauncher/files/883540/unchanged.txt)

For backup, I got a fork of it, before this was pushed, if we would miss something.  
There was very much trash files in the repo :smile: 

**Please do a fresh clone now. Delete your local copy of OpenLauncher/move to backup. So these files do not get back into the repo.**
