### ISSUE TITLE
Hard to Make Folders in android 7.0

### ISSUE THREAD

**Issue by TeamBrainStorm** [BennyKok/OpenLauncher#3]
Hello On android 7.0 once you add one icon onto the home screen you can't add any more icons 

I thought I'd let you know

**Comment by BennyKok** [comment]
Thanks, but have you tried drop another app on to the folder, or did you mean the rearanging the app in the folder?

**Comment by BennyKok** [comment]
btw the if you are using the apk downloaded from the google drive , it was not the newest.

**Comment by TeamBrainStorm** [comment]
Maybe I worded it wrong once I make a folder I can't put any shortcuts on the home screen And I am building from source Hope that helps :)

**Comment by BennyKok** [comment]
I still don't quite understand what is the problem that you have uncounted, but I am going rewrite the ui as it is very messy now and some part of the launcher and finally the folder system will also be revamped.

**Comment by TeamBrainStorm** [comment]
I took a screencast of the issue
heres the link:
https://drive.google.com/open?id=0B0GHlGFNk1eSODBLQXJxeEJ3d0E

this seems to only be a issue in 7.0 in 6.0.1 it works just fine!

Thanks in advance!

**Comment by BennyKok** [comment]
After seeing the video , i really dont know what which part of the code is going wrong, I think I need to install the emulator to test it on android 7.0 .Thanks, you are really nice.

**Comment by BennyKok** [comment]
I just checked online, the drag behavior on android 7.0 somehow different from 5.0 and 6,.0 ,ah....

**Comment by TeamBrainStorm** [comment]
Hope my screencast helped you out let me know when you fix the issue i'll
test it for you!

**Comment by BennyKok** [comment]
Thx , I will fix the problem as soon as possible.

**Comment by TeamBrainStorm** [comment]
No problem let me know when you do and I'll be your Android 7.0 tester

**Comment by BennyKok** [comment]
thx

**Comment by BennyKok** [comment]
Yeah, fixed, I tried on my 7.0 emulator, and now it works perfectly, compile the source and give it a go. Thanks. Some additional info , I do that by removing the nested `OnDragListener` and found another way to intercept the drop over event for folder item.

**Comment by TeamBrainStorm** [comment]
Yeah it works great on android 7.1.1 I'll test it on my android 7.0 device later on today and let you know :)

**Comment by TeamBrainStorm** [comment]
I just tested it on my android 7.0 device making folders works now but you can only have 1 icon on your home screen check the screencast link

Please let my know if you have any questions


[https://drive.google.com/open?id=0B0GHlGFNk1eScXVtdFVnTk16T25ZRUI2OEYwTlU2OUhtcEQ0](url)

**Comment by BennyKok** [comment]
But it works perfectly on android 7.1.1?

**Comment by BennyKok** [comment]
Oh i will try to fix that.

**Comment by TeamBrainStorm** [comment]
Yes it works just fine in 7.1.1 but on 7.0 is the result of that screen
cast

**Comment by BennyKok** [comment]
I will look for the problem again, and I find out that the emulator I am using was >7.0, however I will fix that asap.

**Comment by BennyKok** [comment]
Can you please try again, I have double tested on my 7.0 emulator and it works, I really don't know what happened on you device. Are you sure you have compiled the latest source? Or maybe you can try to installed the debug apk in the launcher module's output directory. Thanks 

https://drive.google.com/file/d/0Bzv4cvBCpP9SckQyNHVRV19iNlk/view?usp=sharing

**Comment by TeamBrainStorm** [comment]
I'll test the apk tonight and let you know what I find out!

**Comment by TeamBrainStorm** [comment]
sorry for such a late reply I just got around to checking it and I'm happy to report this issue is now fixed On android 7.0.0!

**Comment by BennyKok** [comment]
Oh it is never too late, and after fixing some other current issue, I will start the ios style desktop development as you suggested.

**Comment by TeamBrainStorm** [comment]
Awesome let me know if you need any help with that I look forward to
testing that feature!

**Comment by BennyKok** [comment]
Great , so I guess , I can now close this issue.

**Comment by TeamBrainStorm** [comment]
Yep!
