### ISSUE TITLE
Cancel does not Cancel

### ISSUE THREAD

**Issue by grrrrr** [BennyKok/OpenLauncher#31]
Android 7.1.1 (LineageOS)
OpenLauncher alpha2_patch2  (f-droid)

**What is happening:**

In the settings, any option that has an `ok`/`cancel` button, the cancel option saves the settings instead of reverting to original settings

- open launcher settings 
- select `App Drawer` -> `Size` ( defaults to Columns 4 / Rows 5)
- move the slider to change the size, e.g. Rows to `6`
- touch `Cancel`
- Open the setting again
- Rows is still 6 instead of being set back to 5

**What should happen**

The use of the cancel button should revert any changes to settings instead of making them active.

**Comment by dkanada** [comment]
Should be fixed now.
