### ISSUE TITLE
Hide OpenLauncher in the drawer or name it like "OL Settings"

### ISSUE THREAD

**Issue by OffifialMITX** [BennyKok/OpenLauncher#34]
It's kinda pointless.

**Comment by grrrrr** [comment]
It gives you access to settings

**Comment by OffifialMITX** [comment]
I noticed but it's pretty misleading, changed the title.

**Comment by gsantner** [comment]
As I am currently testing and developing on OpenLauncher, it's pretty nice to have it also in launchers, so I can open it while having my other on still as default. Others (e.g. Nova) also have an launcher named Nova, I cannot see any problem in here :smile: 

But still, if you want this, this can be done in about 2-3 lines of code for functionality + a preference option.

**Comment by dkanada** [comment]
I actually like the current solution, but if I had to choose I would say hide the icon rather than rename it. The ideal solution here is to leave it as is but add the option to modify individual apps similar to Nova's implementation. That would require a lot of work but would allow for renaming apps and shortcuts, changing individual icons, et cetera. What do you think @BennyKok?

**Comment by OffifialMITX** [comment]
I think you're not getting my point. What I actually mean is that in the current state it is not clear that that opening "OpenLauncher" inside of OpenLauncher opens OpenLauncher's settings and not (as it seemed for me, at least) just reopens the launcher itself (Like e.g. SilverFish currently does).

The simplest solution in my opinion is to just add "settings" in the name.

**Comment by gsantner** [comment]
I think @dkanada 's commen notices a top missing feature of OpenLauncher currently. Adding this feature should also resolve your issue @OffifialMITX , right? As I'm also using Nova currently, I also like how its done there.

**Comment by OffifialMITX** [comment]
Sure.

**Comment by BennyKok** [comment]
I think the I will force to change the name to OLSettings and we will leave it there until we implement individual name etc and we'll see then. @dkanada

**Comment by BennyKok** [comment]
Great
