### ISSUE TITLE
Change size dialog bug (gfx)

### ISSUE THREAD

**Issue by OffifialMITX** [BennyKok/OpenLauncher#37]
Every change size dialog is shaking up and down and does not show changes until closed and reopened.
Android 5.1.1 (Stock)
Screen: 480x854
Build: 1st one in F-Droid repo

**Comment by dkanada** [comment]
A video of the issue would be very helpful, this sounds like it will be hard to debug.

**Comment by OffifialMITX** [comment]
I'll try to make one today.

**Comment by BennyKok** [comment]
I have experienced this bug long times ago, it is the problem of the ConstrainLayout and the MaterialDialog , now it seems ok cause I switched to RelativeLayout.
