### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by vapingisgood4u** [BennyKok/OpenLauncher#4]
Would you consider submitting this app to F-Droid?

**Comment by BennyKok** [comment]
OH, very good suggestion.

**Comment by BennyKok** [comment]
Do you have any ideas how to do that? I mean via the git repository of F-Droid.

**Comment by zachberger** [comment]
You will have to ensure that you meet the inclusion policy located [here](https://f-droid.org/wiki/page/Inclusion_Policy). Once you've ensured you have met the crietria you place this app in the submission queue located [here](https://f-droid.org/forums/forum/submission-queue/). More details are available on [this page](https://f-droid.org/wiki/page/Inclusion_How-To).

**Comment by BennyKok** [comment]
Right

**Comment by BennyKok** [comment]
Ok , put in the submission queue, I will close this after it is on F-Droid.

**Comment by BennyKok** [comment]
I have put in the submission queue, however this project uses the Constraint Layout, which is in the alpha status, and they said this can be only available on F-Droid if the Constraint Layout becomes stable.

**Comment by BennyKok** [comment]
Just resubmitted to F droid, wait and see

**Comment by offa** [comment]
The issue has been closed with an "added" label. However it's not available through fdroid yet. According to the Fdroid issue, there's a build failure: https://gitlab.com/fdroid/rfp/issues/58

**Comment by BennyKok** [comment]
@offa  I have update the ConstraintLayout to the stable version, will that be ok now.

**Comment by offa** [comment]
Thanks, I can't wait to get OpenLauncher through Fdroid (instead of building from source every time)! 👍

**Comment by offa** [comment]
OpenLauncher is now available on F-Droid!? But the Link on the F-Droid website [is dead](https://f-droid.org/repository/browse/?fdid=com.benny.openlauncher).

Is this release intended and ready to use or by accident?

**Comment by offa** [comment]
While the [related issue](https://gitlab.com/fdroid/rfp/issues/58) does not have any news, the [wiki](https://f-droid.org/wiki/page/OpenLauncher) states it's available now – the latest version.

**Comment by BennyKok** [comment]
I dont know what is happening on f droid, but previously, they said google
hasnt added the constraint layout to the repo that used by f droid, so the
lib want not found and a build error happened, but now I still dont know, I
will need to check it up when i back home on my pc.

**Comment by BennyKok** [comment]
Ok now, lets close this old 'issue' 😆
