### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by caiqingchong1989** [BennyKok/OpenLauncher#43]
![default](https://cloud.githubusercontent.com/assets/9217382/24534755/885a65b6-1602-11e7-8f49-c94c72e4088c.png)

**Comment by gsantner** [comment]
This is not an issue of OpenLauncher. Check your Internet connection, Android SDK installation, and be sure you have accepted the licenses.

Maybe the echos of <https://gitlab.com/fdroid/fdroidserver/merge_requests/225/diffs#55bf5e6391d4e4297af5d0a50c839d60b05f8fa9>  + write access to android sdk resolves your problem.

I made a fresh clone, and did `gradle assemble` without any issues.
