### ISSUE TITLE
Searchbar on desktop

### ISSUE THREAD

**Issue by scoute-dich** [BennyKok/OpenLauncher#7]
When I disable the search bar on the desktop, open the app drawer and go back to the desktop, the search bar is there again, although it is still disabled in the settings.

**Comment by scoute-dich** [comment]
This happens not when I leave an app to go to the home screen, only from app drawer.

Btw. I'm using CM14.1 (Android 7.1.1).

**Comment by BennyKok** [comment]
Did this closed automatically when I merged your request?? So interesting.
