### ISSUE TITLE
[Feature request] Hide App labels on Desktop

### ISSUE THREAD

**Issue by flocke** [BennyKok/OpenLauncher#8]
I've recently started using OpenLauncher on my Nexus 5X and I really like it so far.

The only request I have (since a hide apps feature is already in development) is an option to hide the labels of Apps on the Desktop (similar to the hide label option for the Dock).

Thanks and keep up the great work!

**Comment by dkanada** [comment]
+1

I would also like to suggest an option to hide the scroll bar in the app drawer. This app looks great and I can't wait to see it on F-Droid!

**Comment by BennyKok** [comment]
Ok, the F-Droid things is a problem as they wont put this project in F-Droid if this launcher still using the alpha version of Constraint layout.

**Comment by BennyKok** [comment]
The two features were added in the latest commit
